### PR TITLE
Broader analyzer constraints

### PR DESCRIPTION
**Pull request by stevenroose**
I'll test this in a second

### CODE REVIEW

**Comment by stevenroose** [comment]
The `dartson_test.dart` tests all pass. The `transformer_test.dart` tests too, but with a warning:
```
$ dart test/transformer_test.dart 
00:00 +0: read source code from file
00:00 +1: should contain the SimpleClass declaration
00:00 +2: should find a SimpleIdentifier prefix for the dartson import
00:00 +2 ~1: should show the metadata
00:00 +3 ~1: the compiler should contain the SimpleClass
00:00 +4 ~1: fetch entity map from simpleClass
00:00 +5 ~1: build and compile code
Generating code into: /tmp/dartson_Wvpdbm
00:00 +6 ~1: All tests passed!
```

**Comment by stevenroose** [comment]
I have a project that uses Angular2 and `reflectable`. It was not able to find dependencies with dartson 0.2.5, but it could with this edit. 
(The analyzer version it found was `0.27.3`.

**Comment by Ne4istb** [comment]
I also need it. @eredo what does stop you from merging this PR?

**Comment by stevenroose** [comment]
You can temporarily fork the repo, merge the PR in your master branch and add a Git dependency to your pubspec file.

However, I would prefer to have this merged as well. @eredo, I would be willing to help maintain this repo if you no longer want to, just add me to the repo and to the pub page.

**Comment by Ne4istb** [comment]
@stevenroose already did it)) But i guess this fix is needed for other developers as well so it's better to have it published.

**Comment by eredo** [comment]
I'm sorry for my absence. I'll now continue to support this repository and also add new functionality to dartson.

**Comment by stevenroose** [comment]
Super, thanks! Don't forget to publish the new version to pub!

**Comment by eredo** [comment]
Done! 0.2.6 is available on pub.

**Pull request merged**
